name: dart_build
version: 0.1.0+dart2
author: Rob Becker <rob.becker@workiva.com>
homepage: https://github.com/Workiva/dart_build
description: A command line tool that provides Dart 1 & 2 compatible build & serve commands to ease the transition to Dart 2.

# Dart 1
# environment:
#   sdk: ">=1.24.2 <2.0.0-dev.51.0"

# Dart 2
environment: # dev 51 removes pub build/serve
  sdk: ">=2.0.0-dev.51.0 <2.0.0" # TODO update once Dart 2 stable releases

dependencies:
  io: ^0.3.2+1
  path: ^1.5.1
  stack_trace: ^1.9.2

  # For Dart 2 use build runner
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.1

executables:
  dart_build:
