name: dart_build
version: 0.1.0
author: Rob Becker <rob.becker@workiva.com>
homepage: https://github.com/Workiva/dart_build
description: A CLI that provides dart 1 and dart 2 compatible build and serve commands

# Dart 1
environment:
  sdk: ">=1.24.2 <2.0.0"

# Dart 2
# environment:
#   sdk: ">=2.0.0-dev.32.0 <2.0.0" # TODO update once Dart 2 stable releases

dependencies:
  args: ">=0.13.7 < 2.0.0"
  io: ^0.3.2+1
  meta: ^1.1.2
  path: ^1.5.1
  pub_semver: ^1.3.2
  stack_trace: ^1.9.2
  yaml: ^2.1.13

  # For Dart 2 use build runner
  # build_runner: ^0.8.0
  # build_web_compilers: ^0.3.1

executables:
  dart_build:
